import { Language, Cuisine } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'Hindi' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'kn', name: 'Kannada' },
  { code: 'bn', name: 'Bengali' },
  { code: 'te', name: 'Telugu' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'ur', name: 'Urdu' },
];

export const CUISINES: Cuisine[] = [
  { id: 'indian', name: 'Indian' },
  { id: 'mexican', name: 'Mexican' },
  { id: 'italian', name: 'Italian' },
  { id: 'chinese', name: 'Chinese' },
  { id: 'thai', name: 'Thai' },
  { id: 'french', name: 'French' },
  { id: 'japanese', name: 'Japanese' },
  { id: 'mediterranean', name: 'Mediterranean' },
  { id: 'middle_eastern', name: 'Middle Eastern' },
  { id: 'vietnamese', name: 'Vietnamese' },
  { id: 'american', name: 'American' },
  { id: 'african', name: 'African' },
  { id: 'spanish', name: 'Spanish' },
  { id: 'korean', name: 'Korean' },
  { id: 'greek', name: 'Greek' },
  { id: 'turkish', name: 'Turkish' },
];

type Translations = {
  [key: string]: any;
};

export const translations: Translations = {
  en: {
    greeting: "Hi there! I’m Chef BOT, your friendly kitchen companion. Let’s cook something delicious today! 🍳✨",
    selectLang: "Please select your preferred language:",
    selectCuisine: "Which cuisine would you like to try today?",
    whatDish: (cuisine: string) => `What ${cuisine} dish would you like the recipe for? You can also ask me any other question!`,
    saveRecipe: "Save Recipe",
    viewSources: "View Sources",
    sources: "Sources",
    recipeSaved: "Chef BOT: Recipe saved successfully.",
    showMyRecipes: "Show my saved recipes",
    sourcesLink: "Sources:",
    sourcesNotFound: "Chef BOT: No working YouTube videos available for this recipe.",
    recipeError: "Oh no! I had a little hiccup in my kitchen. I couldn't find that dish.",
    textPlaceholder: "Ask for a recipe or question...",
    recipePlaceholder: "Ask about this recipe or find another...",
    remove: "Remove",
    recipeRemoved: (recipeName: string) => `${recipeName} has been removed from your saved recipes.`,
    suggestions: "How about one of these instead?",
    askAnotherRecipe: "Would you like to find another recipe?",
    yesSearchAnother: "Yes, search another recipe",
    noImDone: "No, I’m done",
    whatDish_short: "Great! What dish are you looking for?",
    goodbye: "Happy cooking! Let me know if you need anything else. Goodbye! 👋",
  },
  hi: {
    greeting: "नमस्ते! मैं शेफ बॉट हूं, आपका दोस्ताना रसोई साथी। आइए आज कुछ स्वादिष्ट बनाएं! 🍳✨",
    selectLang: "कृपया अपनी पसंदीदा भाषा चुनें:",
    selectCuisine: "आज आप कौन सा व्यंजन आज़माना चाहेंगे?",
    whatDish: (cuisine: string) => `${cuisine} डिश में से आप किसकी रेसिपी चाहेंगे? आप मुझसे कोई और सवाल भी पूछ सकते हैं!`,
    saveRecipe: "रेसिपी सहेजें",
    viewSources: "स्रोत देखें",
    sources: "सूत्र",
    recipeSaved: "शेफ बॉट: रेसिपी सफलतापूर्वक सहेजी गई।",
    showMyRecipes: "मेरी सहेजी गई रेसिपी दिखाओ",
    sourcesLink: "सूत्र:",
    sourcesNotFound: "शेफ बॉट: इस रेसिपी के लिए कोई काम करने वाले यूट्यूब वीडियो उपलब्ध नहीं हैं।",
    recipeError: "ओह नहीं! मेरी रसोई में थोड़ी गड़बड़ हो गई। मुझे वह डिश नहीं मिली।",
    textPlaceholder: "कोई रेसिपी या सवाल पूछें...",
    recipePlaceholder: "इस रेसिपी के बारे में पूछें या कोई और ढूंढें...",
    remove: "हटा दें",
    recipeRemoved: (recipeName: string) => `${recipeName} को आपकी सहेजी गई रेसिपी से हटा दिया गया है।`,
    suggestions: "इनमें से किसी एक के बारे में क्या ख़याल है?",
    askAnotherRecipe: "क्या आप कोई और रेसिपी खोजना चाहेंगे?",
    yesSearchAnother: "हाँ, दूसरी रेसिपी खोजें",
    noImDone: "नहीं, मेरा हो गया",
    whatDish_short: "बढ़िया! आप कौन सी डिश ढूंढ रहे हैं?",
    goodbye: "खाना पकाने में आनंद लें! अगर आपको किसी और चीज़ की ज़रूरत हो तो मुझे बताएं। अलविदा! 👋",
  },
  mr: {
    greeting: "नमस्कार! मी शेफ बॉट आहे, तुमचा स्वयंपाकघरातील सोबती. चला आज काहीतरी स्वादिष्ट बनवूया! 🍳✨",
    selectLang: "कृपया तुमची आवडती भाषा निवडा:",
    selectCuisine: "आज तुम्हाला कोणते खाद्यप्रकार करून बघायला आवडेल?",
    whatDish: (cuisine: string) => `तुम्हाला कोणत्या ${cuisine} पदार्थाची रेसिपी हवी आहे? तुम्ही मला इतर कोणताही प्रश्न विचारू शकता!`,
    saveRecipe: "रेसिपी जतन करा",
    viewSources: "स्रोत पहा",
    sources: "स्रोत",
    recipeSaved: "शेफ बॉट: रेसिपी यशस्वीरित्या जतन झाली.",
    showMyRecipes: "माझ्या जतन केलेल्या पाककृती दर्शवा",
    sourcesLink: "स्रोत:",
    sourcesNotFound: "शेफ बॉट: या रेसिपीसाठी कोणतेही कार्यरत YouTube व्हिडिओ उपलब्ध नाहीत.",
    recipeError: "अरेरे! माझ्या स्वयंपाकघरात थोडी अडचण आली. मला तो पदार्थ सापडला नाही.",
    textPlaceholder: "एक कृती किंवा प्रश्न विचारा...",
    recipePlaceholder: "या रेसिपीबद्दल विचारा किंवा दुसरी शोधा...",
    remove: "काढून टाका",
    recipeRemoved: (recipeName: string) => `${recipeName} तुमच्या जतन केलेल्या पाककृतींमधून काढून टाकण्यात आले आहे.`,
    suggestions: "याऐवजी यापैकी एकाबद्दल काय?",
    askAnotherRecipe: "तुम्हाला दुसरी रेसिपी शोधायला आवडेल का?",
    yesSearchAnother: "होय, दुसरी रेसिपी शोधा",
    noImDone: "नाही, माझे झाले",
    whatDish_short: "उत्तम! तुम्ही कोणता पदार्थ शोधत आहात?",
    goodbye: "स्वयंपाकाचा आनंद घ्या! तुम्हाला आणखी काही हवे असल्यास मला सांगा. अलविदा! 👋",
  },
  ta: {
    greeting: "வணக்கம்! நான் செஃப் பாட், உங்கள் நட்பு சமையலறை துணை. இன்று சுவையான ஒன்றை சமைப்போம்! 🍳✨",
    selectLang: "தயவுசெய்து உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்:",
    selectCuisine: "இன்று எந்த சமையலை முயற்சிக்க விரும்புகிறீர்கள்?",
    whatDish: (cuisine: string) => `எந்த ${cuisine} உணவிற்கான செய்முறையை நீங்கள் விரும்புகிறீர்கள்? நீங்கள் என்னிடம் வேறு எந்த கேள்வியையும் கேட்கலாம்!`,
    saveRecipe: "செய்முறையை சேமி",
    viewSources: "ஆதாரங்களைக் காண்க",
    sources: "ஆதாரங்கள்",
    recipeSaved: "செஃப் பாட்: செய்முறை வெற்றிகரமாக சேமிக்கப்பட்டது.",
    showMyRecipes: "எனது சேமித்த சமையல் குறிப்புகளைக் காட்டு",
    sourcesLink: "ஆதாரங்கள்:",
    sourcesNotFound: "செஃப் பாட்: இந்த செய்முறைக்கு வேலை செய்யும் யூடியூப் வீடியோக்கள் எதுவும் கிடைக்கவில்லை.",
    recipeError: "ஓ இல்லை! என் சமையலறையில் ஒரு சிறிய தடுமாற்றம் ஏற்பட்டது. அந்த உணவை என்னால் கண்டுபிடிக்க முடியவில்லை.",
    textPlaceholder: "ஒரு செய்முறை அல்லது கேள்வியைக் கேளுங்கள்...",
    recipePlaceholder: "இந்த செய்முறையைப் பற்றி கேளுங்கள் அல்லது இன்னொன்றைக் கண்டுபிடி...",
    remove: "அகற்று",
    recipeRemoved: (recipeName: string) => `${recipeName} உங்கள் சேமித்த சமையல் குறிப்புகளிலிருந்து அகற்றப்பட்டது.`,
    suggestions: "அதற்கு பதிலாக இவற்றில் ஒன்று எப்படி?",
    askAnotherRecipe: "நீங்கள் மற்றொரு செய்முறையைக் கண்டுபிடிக்க விரும்புகிறீர்களா?",
    yesSearchAnother: "ஆம், மற்றொரு செய்முறையைத் தேடுங்கள்",
    noImDone: "இல்லை, நான் முடித்துவிட்டேன்",
    whatDish_short: "அருமை! நீங்கள் எந்த உணவைத் தேடுகிறீர்கள்?",
    goodbye: "சமையலை மகிழுங்கள்! உங்களுக்கு வேறு ஏதாவது தேவைப்பட்டால் எனக்குத் தெரியப்படுத்துங்கள். வருகிறேன்! 👋",
  },
  gu: {
    greeting: "કેમ છો! હું શેફ બોટ છું, તમારો મૈત્રીપૂર્ણ રસોડાનો સાથી. ચાલો આજે કંઈક સ્વાદિષ્ટ બનાવીએ! 🍳✨",
    selectLang: "કૃપા કરીને તમારી પસંદગીની ભાષા પસંદ કરો:",
    selectCuisine: "આજે તમે કઈ વાનગી અજમાવવા માંગો છો?",
    whatDish: (cuisine: string) => `તમે કઈ ${cuisine} વાનગીની રેસીપી ઈચ્છો છો? તમે મને બીજો કોઈ પ્રશ્ન પણ પૂછી શકો છો!`,
    saveRecipe: "રેસીપી સાચવો",
    viewSources: "સ્ત્રોતો જુઓ",
    sources: "સ્ત્રોતો",
    recipeSaved: "શેફ બોટ: રેસીપી સફળતાપૂર્વક સાચવવામાં આવી.",
    showMyRecipes: "મારી સાચવેલી રેસિપી બતાવો",
    sourcesLink: "સ્ત્રોતો:",
    sourcesNotFound: "શેફ બોટ: આ રેસીપી માટે કોઈ કાર્યરત YouTube વિડિઓઝ ઉપલબ્ધ નથી.",
    recipeError: "અરે નહિ! મારા રસોડામાં થોડી ગરબડ થઈ ગઈ. મને તે વાનગી મળી નહીં.",
    textPlaceholder: "એક રેસીપી અથવા પ્રશ્ન પૂછો...",
    recipePlaceholder: "આ રેસીપી વિશે પૂછો અથવા બીજી શોધો...",
    remove: "દૂર કરો",
    recipeRemoved: (recipeName: string) => `${recipeName} તમારી સાચવેલી વાનગીઓમાંથી દૂર કરવામાં આવી છે.`,
    suggestions: "તેના બદલે આમાંથી એક વિશે શું?",
    askAnotherRecipe: "શું તમે બીજી રેસીપી શોધવા માંગો છો?",
    yesSearchAnother: "હા, બીજી રેસીપી શોધો",
    noImDone: "ના, હું થઈ ગયો",
    whatDish_short: "સરસ! તમે કઈ વાનગી શોધી રહ્યા છો?",
    goodbye: "રસોઈનો આનંદ માણો! જો તમને başka કંઈપણની જરૂર હોય તો મને જણાવો. આવજો! 👋",
  },
  kn: {
    greeting: "ನಮಸ್ಕಾರ! ನಾನು ಶೆಫ್ ಬಾಟ್, ನಿಮ್ಮ ಸ್ನೇಹಪರ ಅಡುಗೆಮನೆಯ ಸಂಗಾತಿ. ಇಂದು ಏನಾದರೂ ರುಚಿಕರವಾದದ್ದನ್ನು ಅಡುಗೆ ಮಾಡೋಣ! 🍳✨",
    selectLang: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
    selectCuisine: "ಇಂದು ನೀವು ಯಾವ ಪಾಕಪದ್ಧತಿಯನ್ನು ಪ್ರಯತ್ನಿಸಲು ಬಯಸುತ್ತೀರಿ?",
    whatDish: (cuisine: string) => `ನೀವು ಯಾವ ${cuisine} ಖಾದ್ಯದ ಪಾಕವಿಧಾನವನ್ನು ಬಯಸುತ್ತೀರಿ? ನೀವು ನನ್ನನ್ನು ಬೇರೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಬಹುದು!`,
    saveRecipe: "ಪಾಕವಿಧಾನವನ್ನು ಉಳಿಸಿ",
    viewSources: "ಮೂಲಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    sources: "ಮೂಲಗಳು",
    recipeSaved: "ಶೆಫ್ ಬಾಟ್: ಪಾಕವಿಧಾನವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ.",
    showMyRecipes: "ನನ್ನ ಉಳಿಸಿದ ಪಾಕವಿಧಾನಗಳನ್ನು ತೋರಿಸಿ",
    sourcesLink: "ಮೂಲಗಳು:",
    sourcesNotFound: "ಶೆಫ್ ಬಾಟ್: ಈ ಪಾಕವಿಧಾನಕ್ಕಾಗಿ ಯಾವುದೇ ಕೆಲಸ ಮಾಡುವ ಯೂಟ್ಯೂಬ್ ವೀಡಿಯೊಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    recipeError: "ಓಹ್ ಇಲ್ಲ! ನನ್ನ ಅಡುಗೆಮನೆಯಲ್ಲಿ ಸ್ವಲ್ಪ ತೊಡಕು ಉಂಟಾಯಿತು. ನನಗೆ ಆ ಖಾದ್ಯ ಸಿಗಲಿಲ್ಲ.",
    textPlaceholder: "ಪಾಕವಿಧಾನ ಅಥವಾ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...",
    recipePlaceholder: "ಈ ಪಾಕವಿಧಾನದ ಬಗ್ಗೆ ಕೇಳಿ ಅಥವಾ ಇನ್ನೊಂದನ್ನು ಹುಡುಕಿ...",
    remove: "ತೆಗೆದುಹಾಕಿ",
    recipeRemoved: (recipeName: string) => `${recipeName} ಅನ್ನು ನಿಮ್ಮ ಉಳಿಸಿದ ಪಾಕವಿಧಾನಗಳಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.`,
    suggestions: "ಬದಲಾಗಿ ಇವುಗಳಲ್ಲಿ ಒಂದನ್ನು ಹೇಗೆ?",
    askAnotherRecipe: "ನೀವು ಇನ್ನೊಂದು ಪಾಕವಿಧಾನವನ್ನು ಹುಡುಕಲು ಬಯಸುವಿರಾ?",
    yesSearchAnother: "ಹೌದು, ಇನ್ನೊಂದು ಪಾಕವಿಧಾನವನ್ನು ಹುಡುಕಿ",
    noImDone: "ಇಲ್ಲ, ನಾನು ಮುಗಿಸಿದ್ದೇನೆ",
    whatDish_short: "ಅದ್ಭುತ! ನೀವು ಯಾವ ಖಾದ್ಯವನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?",
    goodbye: "ಅಡುಗೆಯನ್ನು ಆನಂದಿಸಿ! ನಿಮಗೆ ಬೇರೆನಾದರೂ ಬೇಕಿದ್ದರೆ ನನಗೆ ತಿಳಿಸಿ. ವಿದಾಯ! 👋",
  },
  bn: {
    greeting: "নমস্কার! আমি শেফ বট, আপনার বন্ধুত্বপূর্ণ রান্নাঘরের সঙ্গী। চলুন আজ সুস্বাদু কিছু রান্না করা যাক! 🍳✨",
    selectLang: "অনুগ্রহ করে আপনার পছন্দের ভাষা নির্বাচন করুন:",
    selectCuisine: "আজ আপনি কোন রান্না চেষ্টা করতে চান?",
    whatDish: (cuisine: string) => `আপনি কোন ${cuisine} খাবারের রেসিপি চান? আপনি আমাকে অন্য কোন প্রশ্নও করতে পারেন!`,
    saveRecipe: "রেসিপি সংরক্ষণ করুন",
    viewSources: "উৎস দেখুন",
    sources: "উৎস",
    recipeSaved: "শেফ বট: রেসিপি সফলভাবে সংরক্ষিত হয়েছে।",
    showMyRecipes: "আমার সংরক্ষিত রেসিপিগুলি দেখান",
    sourcesLink: "উৎস:",
    sourcesNotFound: "শেফ বট: এই রেসিপির জন্য কোনো কার্যকরী ইউটিউব ভিডিও পাওয়া যায়নি।",
    recipeError: "ওহ না! আমার রান্নাঘরে একটু সমস্যা হয়েছে। আমি সেই ডিশটি খুঁজে পাইনি।",
    textPlaceholder: "একটি রেসিপি বা প্রশ্ন জিজ্ঞাসা করুন...",
    recipePlaceholder: "এই রেসিপি সম্পর্কে জিজ্ঞাসা করুন বা অন্য একটি খুঁজুন...",
    remove: "অপসারণ করুন",
    recipeRemoved: (recipeName: string) => `${recipeName} আপনার সংরক্ষিত রেসিপি থেকে সরানো হয়েছে।`,
    suggestions: "পরিবর্তে এইগুলির মধ্যে একটি কেমন?",
    askAnotherRecipe: "আপনি কি অন্য একটি রেসিপি খুঁজে পেতে চান?",
    yesSearchAnother: "হ্যাঁ, অন্য রেসিপি অনুসন্ধান করুন",
    noImDone: "না, আমার কাজ শেষ",
    whatDish_short: "দারুণ! আপনি কোন ডিশ খুঁজছেন?",
    goodbye: " রান্না উপভোগ করুন! আপনার যদি অন্য কিছুর প্রয়োজন হয় তবে আমাকে জানান। বিদায়! 👋",
  },
  te: {
    greeting: "నమస్కారం! నేను చెఫ్ బాట్, మీ స్నేహపూర్వక వంటగది సహచరుడిని. ఈ రోజు రుచికరమైనది వండుదాం! 🍳✨",
    selectLang: "దయచేసి మీకు ఇష్టమైన భాషను ఎంచుకోండి:",
    selectCuisine: "ఈ రోజు మీరు ఏ వంటకాన్ని ప్రయత్నించాలనుకుంటున్నారు?",
    whatDish: (cuisine: string) => `మీరు ఏ ${cuisine} వంటకం కోసం రెసిపీని కోరుకుంటున్నారు? మీరు నన్ను ఏ ఇతర ప్రశ్న అయినా అడగవచ్చు!`,
    saveRecipe: "రెసిపీని సేవ్ చేయండి",
    viewSources: "మూలాలను వీక్షించండి",
    sources: "మూలాలు",
    recipeSaved: "చెఫ్ బాట్: రెసిపీ విజయవంతంగా సేవ్ చేయబడింది.",
    showMyRecipes: "నా సేవ్ చేసిన రెసిపీలను చూపించు",
    sourcesLink: "మూలాలు:",
    sourcesNotFound: "చెఫ్ బాట్: ఈ రెసిపీ కోసం పని చేసే యూట్యూబ్ వీడియోలు ఏవీ అందుబాటులో లేవు.",
    recipeError: "అయ్యో! నా వంటగదిలో కొంచెం సమస్య వచ్చింది. నేను ఆ వంటకాన్ని కనుగొనలేకపోయాను.",
    textPlaceholder: "ఒక రెసిపీ లేదా ప్రశ్న అడగండి...",
    recipePlaceholder: "ఈ రెసిపీ గురించి అడగండి లేదా మరొకటి కనుగొనండి...",
    remove: "తొలగించు",
    recipeRemoved: (recipeName: string) => `${recipeName} మీ సేవ్ చేసిన రెసిపీల నుండి తీసివేయబడింది.`,
    suggestions: "దానికి బదులుగా వీటిలో ఒకటి ఎలా ఉంటుంది?",
    askAnotherRecipe: "మీరు మరొక రెసిపీని కనుగొనాలనుకుంటున్నారా?",
    yesSearchAnother: "అవును, మరొక రెసిపీని శోధించండి",
    noImDone: "లేదు, నేను పూర్తి చేసాను",
    whatDish_short: "గొప్పది! మీరు ఏ వంటకం కోసం చూస్తున్నారు?",
    goodbye: "వంటను ఆస్వాదించండి! మీకు ఇంకేమైనా కావాలంటే నాకు తెలియజేయండి. వీడ్కోలు! 👋",
  },
  pa: {
    greeting: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਸ਼ੈੱਫ ਬੋਟ ਹਾਂ, ਤੁਹਾਡਾ ਦੋਸਤਾਨਾ ਰਸੋਈ ਸਾਥੀ। ਆਓ ਅੱਜ ਕੁਝ ਸੁਆਦੀ ਪਕਾਈਏ! 🍳✨",
    selectLang: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ:",
    selectCuisine: "ਤੁਸੀਂ ਅੱਜ ਕਿਹੜਾ ਪਕਵਾਨ ਅਜ਼ਮਾਉਣਾ ਚਾਹੋਗੇ?",
    whatDish: (cuisine: string) => `ਤੁਸੀਂ ਕਿਸ ${cuisine} ਪਕਵਾਨ ਦੀ ਰੈਸਿਪੀ ਚਾਹੁੰਦੇ ਹੋ? ਤੁਸੀਂ ਮੈਨੂੰ ਕੋਈ ਹੋਰ ਸਵਾਲ ਵੀ ਪੁੱਛ ਸਕਦੇ ਹੋ!`,
    saveRecipe: "ਰੈਸਿਪੀ ਸੇਵ ਕਰੋ",
    viewSources: "ਸਰੋਤ ਵੇਖੋ",
    sources: "ਸਰੋਤ",
    recipeSaved: "ਸ਼ੈੱਫ ਬੋਟ: ਰੈਸਿਪੀ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤੀ ਗਈ।",
    showMyRecipes: "ਮੇਰੀਆਂ ਸੇਵ ਕੀਤੀਆਂ ਰੈਸਿਪੀਜ਼ ਦਿਖਾਓ",
    sourcesLink: "ਸਰੋਤ:",
    sourcesNotFound: "ਸ਼ੈੱਫ ਬੋਟ: ਇਸ ਵਿਅੰਜਨ ਲਈ ਕੋਈ ਕੰਮ ਕਰਨ ਵਾਲੇ ਯੂਟਿਊਬ ਵੀਡੀਓ ਉਪਲਬਧ ਨਹੀਂ ਹਨ।",
    recipeError: "ਓ ਨਹੀਂ! ਮੇਰੀ ਰਸੋਈ ਵਿੱਚ ਥੋੜੀ ਗੜਬੜ ਹੋ ਗਈ ਸੀ। ਮੈਨੂੰ ਉਹ ਪਕਵਾਨ ਨਹੀਂ ਮਿਲਿਆ।",
    textPlaceholder: "ਇੱਕ ਵਿਅੰਜਨ ਜਾਂ ਸਵਾਲ ਪੁੱਛੋ...",
    recipePlaceholder: "ਇਸ ਵਿਅੰਜਨ ਬਾਰੇ ਪੁੱਛੋ ਜਾਂ ਕੋਈ ਹੋਰ ਲੱਭੋ...",
    remove: "ਹਟਾਓ",
    recipeRemoved: (recipeName: string) => `${recipeName} ਨੂੰ ਤੁਹਾਡੀਆਂ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਪਕਵਾਨਾਂ ਤੋਂ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।`,
    suggestions: "ਇਸ ਦੀ ਬਜਾਏ ਇਹਨਾਂ ਵਿੱਚੋਂ ਇੱਕ ਬਾਰੇ ਕੀ?",
    askAnotherRecipe: "ਕੀ ਤੁਸੀਂ ਕੋਈ ਹੋਰ ਵਿਅੰਜਨ ਲੱਭਣਾ ਚਾਹੋਗੇ?",
    yesSearchAnother: "ਹਾਂ, ਕੋਈ ਹੋਰ ਵਿਅੰਜਨ ਲੱਭੋ",
    noImDone: "ਨਹੀਂ, ਮੈਂ ਪੂਰਾ ਕਰ ਲਿਆ",
    whatDish_short: "ਬਹੁਤ ਵਧੀਆ! ਤੁਸੀਂ ਕਿਹੜੀ ਡਿਸ਼ ਲੱਭ ਰਹੇ ਹੋ?",
    goodbye: "ਖਾਣਾ ਪਕਾਉਣ ਦਾ ਅਨੰਦ ਲਓ! ਜੇ ਤੁਹਾਨੂੰ ਕਿਸੇ ਹੋਰ ਚੀਜ਼ ਦੀ ਲੋੜ ਹੈ ਤਾਂ ਮੈਨੂੰ ਦੱਸੋ। ਅਲਵਿਦਾ! 👋",
  },
  ml: {
    greeting: "ഹായ്! ഞാൻ ഷെഫ് ബോട്ട്, നിങ്ങളുടെ സൗഹൃദപരമായ അടുക്കള സഹായി. നമുക്ക് ഇന്ന് രുചികരമായ എന്തെങ്കിലും പാചകം ചെയ്യാം! 🍳✨",
    selectLang: "ദയവായി നിങ്ങളുടെ ഇഷ്ട ഭാഷ തിരഞ്ഞെടുക്കുക:",
    selectCuisine: "ഇന്ന് ഏത് വിഭവം പരീക്ഷിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നു?",
    whatDish: (cuisine: string) => `ഏത് ${cuisine} വിഭവത്തിന്റെ പാചകക്കുറിപ്പാണ് നിങ്ങൾക്ക് വേണ്ടത്? നിങ്ങൾക്ക് എന്നോട് മറ്റേതെങ്കിലും ചോദ്യം ചോദിക്കാം!`,
    saveRecipe: "പാചകക്കുറിപ്പ് സംരക്ഷിക്കുക",
    viewSources: "ഉറവിടങ്ങൾ കാണുക",
    sources: "ഉറവിടങ്ങൾ",
    recipeSaved: "ഷെഫ് ബോട്ട്: പാചകക്കുറിപ്പ് വിജയകരമായി സംരക്ഷിച്ചു.",
    showMyRecipes: "എന്റെ സംരക്ഷിച്ച പാചകക്കുറിപ്പുകൾ കാണിക്കുക",
    sourcesLink: "ഉറവിടങ്ങൾ:",
    sourcesNotFound: "ഷെഫ് ബോട്ട്: ഈ പാചകക്കുറിപ്പിനായി പ്രവർത്തിക്കുന്ന YouTube വീഡിയോകളൊന്നും ലഭ്യമല്ല.",
    recipeError: "ഓ, ഇല്ല! എന്റെ അടുക്കളയിൽ ഒരു ചെറിയ പിശക് സംഭവിച്ചു. എനിക്ക് ആ വിഭവം കണ്ടെത്താനായില്ല.",
    textPlaceholder: "ഒരു പാചകക്കുറിപ്പ് അല്ലെങ്കിൽ ചോദ്യം ചോദിക്കുക...",
    recipePlaceholder: "ഈ പാചകക്കുറിപ്പിനെക്കുറിച്ച് ചോദിക്കുക അല്ലെങ്കിൽ മറ്റൊന്ന് കണ്ടെത്തുക...",
    remove: "നീക്കം ചെയ്യുക",
    recipeRemoved: (recipeName: string) => `${recipeName} നിങ്ങളുടെ സംരക്ഷിച്ച പാചകക്കുറിപ്പുകളിൽ നിന്ന് നീക്കംചെയ്തു.`,
    suggestions: "പകരം ഇവയിലൊന്ന് എങ്ങനെ?",
    askAnotherRecipe: "നിങ്ങൾക്ക് മറ്റൊരു പാചകക്കുറിപ്പ് കണ്ടെത്തണോ?",
    yesSearchAnother: "അതെ, മറ്റൊരു പാചകക്കുറിപ്പ് തിരയുക",
    noImDone: "ഇല്ല, ഞാൻ കഴിഞ്ഞു",
    whatDish_short: "കൊള്ളാം! നിങ്ങൾ ഏത് വിഭവമാണ് തിരയുന്നത്?",
    goodbye: "പാചകം ആസ്വദിക്കൂ! നിങ്ങൾക്ക് മറ്റെന്തെങ്കിലും വേണമെങ്കിൽ എന്നോട് പറയൂ. വിട! 👋",
  },
  ur: {
    greeting: "ہیلو! میں شیف بوٹ ہوں، آپ کا دوستانہ باورچی خانے کا ساتھی۔ آئیے آج کچھ مزیدار پکائیں! 🍳✨",
    selectLang: "براہ کرم اپنی پسندیدہ زبان منتخب کریں:",
    selectCuisine: "آج آپ کون سا کھانا آزمانا چاہیں گے؟",
    whatDish: (cuisine: string) => `آپ کس ${cuisine} ڈش کی ترکیب चाहते ہیں؟ آپ مجھ سے کوئی دوسرا سوال بھی پوچھ سکتے ہیں!`,
    saveRecipe: "ترکیب محفوظ کریں",
    viewSources: "ذرائع دیکھیں",
    sources: "ذرائع",
    recipeSaved: "شیف بوٹ: ترکیب کامیابی سے محفوظ ہو گئی۔",
    showMyRecipes: "میری محفوظ کردہ ترکیبیں دکھائیں",
    sourcesLink: "ذرائع:",
    sourcesNotFound: "شیف بوٹ: اس ترکیب کے لیے کوئی کام کرنے والے یوٹیوب ویڈیوز دستیاب نہیں ہیں۔",
    recipeError: "اوہ نہیں! میرے باورچی خانے میں تھوڑی سی گڑਬੜ ہوگئی۔ مجھے وہ ڈش نہیں ملی۔",
    textPlaceholder: "ایک ہدایت یا سوال پوچھیں...",
    recipePlaceholder: "اس ترکیب کے بارے میں پوچھیں یا کوئی اور تلاش کریں...",
    remove: "حذف کریں",
    recipeRemoved: (recipeName: string) => `${recipeName} کو آپ کی محفوظ کردہ ترکیبوں سے हटा दिया गया ہے۔`,
    suggestions: "اس کے بجائے ان میں سے ایک کے بارے में کیا خیال ہے؟",
    askAnotherRecipe: "کیا آپ کوئی اور ترکیب تلاش کرنا چاہیں گے؟",
    yesSearchAnother: "ہاں، دوسری ترکیب تلاش کریں۔",
    noImDone: "نہیں، میں نے کر लिया",
    whatDish_short: "بہت اچھا! آپ کونسی ڈش تلاش کر رہے ہیں؟",
    goodbye: "کھانا پکانے کا لطف اٹھائیں! اگر آپ کو کسی اور چیز کی ضرورت ہو تو مجھے بتائیں۔ خدا حافظ! 👋",
  },
};