
import { Language, Cuisine } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'Hindi' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'kn', name: 'Kannada' },
  { code: 'bn', name: 'Bengali' },
  { code: 'te', name: 'Telugu' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'ur', name: 'Urdu' },
];

export const CUISINES: Cuisine[] = [
  { id: 'indian', name: 'Indian' },
  { id: 'mexican', name: 'Mexican' },
  { id: 'italian', name: 'Italian' },
  { id: 'chinese', name: 'Chinese' },
  { id: 'thai', name: 'Thai' },
  { id: 'french', name: 'French' },
  { id: 'japanese', name: 'Japanese' },
  { id: 'mediterranean', name: 'Mediterranean' },
  { id: 'middle_eastern', name: 'Middle Eastern' },
  { id: 'vietnamese', name: 'Vietnamese' },
  { id: 'american', name: 'American' },
  { id: 'african', name: 'African' },
  { id: 'spanish', name: 'Spanish' },
  { id: 'korean', name: 'Korean' },
  { id: 'greek', name: 'Greek' },
  { id: 'turkish', name: 'Turkish' },
];

type Translations = {
  [key: string]: any;
};

export const translations: Translations = {
  en: {
    greeting: "Hi there! I’m Chef Board, your friendly kitchen companion. Let’s cook something delicious today! 🍳✨",
    selectLang: "Please select your preferred language:",
    selectCuisine: "Which cuisine would you like to try today?",
    whatDish: (cuisine: string) => `What ${cuisine} dish would you like the recipe for? You can also ask me any other question!`,
    saveRecipe: "Save Recipe",
    viewSources: "View Sources",
    sources: "Sources",
    recipeSaved: (recipeName: string) => `Great choice! I've saved the recipe for ${recipeName} to your cookbook. You can view it anytime by typing "Show my saved recipes". Happy cooking! 📖`,
    showMyRecipes: "Show my saved recipes",
    sourcesLink: "Here are some sources for you:",
    sourcesNotFound: "No valid sources found for this recipe.",
    recipeError: "Oh no! I had a little hiccup in my kitchen. I couldn't find that dish.",
    textPlaceholder: "Ask for a recipe or question...",
    recipePlaceholder: "Ask about this recipe or find another...",
    remove: "Remove",
    recipeRemoved: (recipeName: string) => `${recipeName} has been removed from your saved recipes.`,
    suggestions: "How about one of these instead?",
    noExactMatches: "No valid sources found for this recipe. Here are some related links:",
  },
  hi: {
    greeting: "नमस्ते! मैं शेफ बोर्ड हूं, आपका दोस्ताना रसोई साथी। आइए आज कुछ स्वादिष्ट बनाएं! 🍳✨",
    selectLang: "कृपया अपनी पसंदीदा भाषा चुनें:",
    selectCuisine: "आज आप कौन सा व्यंजन आज़माना चाहेंगे?",
    whatDish: (cuisine: string) => `${cuisine} डिश में से आप किसकी रेसिपी चाहेंगे? आप मुझसे कोई और सवाल भी पूछ सकते हैं!`,
    saveRecipe: "रेसिपी सहेजें",
    viewSources: "स्रोत देखें",
    sources: "सूत्र",
    recipeSaved: (recipeName: string) => `बढ़िया विकल्प! मैंने ${recipeName} की रेसिपी आपकी कुकबुक में सहेज ली है। आप इसे कभी भी "मेरी सहेजी गई रेसिपी दिखाओ" टाइप करके देख सकते हैं। खाना पकाने में आनंद लें! 📖`,
    showMyRecipes: "मेरी सहेजी गई रेसिपी दिखाओ",
    sourcesLink: "आपके लिए कुछ स्रोत यहाँ दिए गए हैं:",
    sourcesNotFound: "इस रेसिपी के लिए कोई वैध स्रोत नहीं मिला।",
    recipeError: "ओह नहीं! मेरी रसोई में थोड़ी गड़बड़ हो गई। मुझे वह डिश नहीं मिली।",
    textPlaceholder: "कोई रेसिपी या सवाल पूछें...",
    recipePlaceholder: "इस रेसिपी के बारे में पूछें या कोई और ढूंढें...",
    remove: "हटा दें",
    recipeRemoved: (recipeName: string) => `${recipeName} को आपकी सहेजी गई रेसिपी से हटा दिया गया है।`,
    suggestions: "इनमें से किसी एक के बारे में क्या ख़याल है?",
    noExactMatches: "इस रेसिपी के लिए कोई वैध स्रोत नहीं मिला। यहाँ कुछ संबंधित लिंक दिए गए हैं:",
  },
  mr: {
    greeting: "नमस्कार! मी शेफ बोर्ड आहे, तुमचा स्वयंपाकघरातील सोबती. चला आज काहीतरी स्वादिष्ट बनवूया! 🍳✨",
    selectLang: "कृपया तुमची आवडती भाषा निवडा:",
    selectCuisine: "आज तुम्हाला कोणते खाद्यप्रकार करून बघायला आवडेल?",
    whatDish: (cuisine: string) => `तुम्हाला कोणत्या ${cuisine} पदार्थाची रेसिपी हवी आहे? तुम्ही मला इतर कोणताही प्रश्न विचारू शकता!`,
    saveRecipe: "रेसिपी जतन करा",
    viewSources: "स्रोत पहा",
    sources: "स्रोत",
    recipeSaved: (recipeName: string) => `उत्तम निवड! मी ${recipeName} ची रेसिपी तुमच्या कुकबुकमध्ये जतन केली आहे. तुम्ही ती कधीही "माझ्या जतन केलेल्या पाककृती दर्शवा" टाइप करून पाहू शकता. आनंदी स्वयंपाक! 📖`,
    showMyRecipes: "माझ्या जतन केलेल्या पाककृती दर्शवा",
    sourcesLink: "तुमच्यासाठी काही स्रोत येथे आहेत:",
    sourcesNotFound: "या रेसिपीसाठी कोणतेही वैध स्रोत आढळले नाहीत.",
    recipeError: "अरेरे! माझ्या स्वयंपाकघरात थोडी अडचण आली. मला तो पदार्थ सापडला नाही.",
    textPlaceholder: "एक कृती किंवा प्रश्न विचारा...",
    recipePlaceholder: "या रेसिपीबद्दल विचारा किंवा दुसरी शोधा...",
    remove: "काढून टाका",
    recipeRemoved: (recipeName: string) => `${recipeName} तुमच्या जतन केलेल्या पाककृतींमधून काढून टाकण्यात आले आहे.`,
    suggestions: "याऐवजी यापैकी एकाबद्दल काय?",
    noExactMatches: "या रेसिपीसाठी कोणतेही वैध स्रोत आढळले नाहीत. येथे काही संबंधित दुवे आहेत:",
  },
  ta: {
    greeting: "வணக்கம்! நான் செஃப் போர்டு, உங்கள் நட்பு சமையலறை துணை. இன்று சுவையான ஒன்றை சமைப்போம்! 🍳✨",
    selectLang: "தயவுசெய்து உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்:",
    selectCuisine: "இன்று எந்த சமையலை முயற்சிக்க விரும்புகிறீர்கள்?",
    whatDish: (cuisine: string) => `எந்த ${cuisine} உணவிற்கான செய்முறையை நீங்கள் விரும்புகிறீர்கள்? நீங்கள் என்னிடம் வேறு எந்த கேள்வியையும் கேட்கலாம்!`,
    saveRecipe: "செய்முறையை சேமி",
    viewSources: "ஆதாரங்களைக் காண்க",
    sources: "ஆதாரங்கள்",
    recipeSaved: (recipeName: string) => `சிறந்த தேர்வு! நான் ${recipeName} செய்முறையை உங்கள் சமையல் புத்தகத்தில் சேமித்துள்ளேன். நீங்கள் எப்போது வேண்டுமானாலும் "எனது சேமித்த சமையல் குறிப்புகளைக் காட்டு" என தட்டச்சு செய்து பார்க்கலாம். மகிழ்ச்சியான சமையல்! 📖`,
    showMyRecipes: "எனது சேமித்த சமையல் குறிப்புகளைக் காட்டு",
    sourcesLink: "உங்களுக்கான சில ஆதாரங்கள் இங்கே:",
    sourcesNotFound: "இந்த செய்முறைக்கு சரியான ஆதாரங்கள் எதுவும் கிடைக்கவில்லை.",
    recipeError: "ஓ இல்லை! என் சமையலறையில் ஒரு சிறிய தடுமாற்றம் ஏற்பட்டது. அந்த உணவை என்னால் கண்டுபிடிக்க முடியவில்லை.",
    textPlaceholder: "ஒரு செய்முறை அல்லது கேள்வியைக் கேளுங்கள்...",
    recipePlaceholder: "இந்த செய்முறையைப் பற்றி கேளுங்கள் அல்லது இன்னொன்றைக் கண்டுபிடி...",
    remove: "அகற்று",
    recipeRemoved: (recipeName: string) => `${recipeName} உங்கள் சேமித்த சமையல் குறிப்புகளிலிருந்து அகற்றப்பட்டது.`,
    suggestions: "அதற்கு பதிலாக இவற்றில் ஒன்று எப்படி?",
    noExactMatches: "இந்த செய்முறைக்கு சரியான ஆதாரங்கள் எதுவும் கிடைக்கவில்லை. இங்கே சில தொடர்புடைய இணைப்புகள் உள்ளன:",
  },
  gu: {
    greeting: "કેમ છો! હું શેફ બોર્ડ છું, તમારો મૈત્રીપૂર્ણ રસોડાનો સાથી. ચાલો આજે કંઈક સ્વાદિષ્ટ બનાવીએ! 🍳✨",
    selectLang: "કૃપા કરીને તમારી પસંદગીની ભાષા પસંદ કરો:",
    selectCuisine: "આજે તમે કઈ વાનગી અજમાવવા માંગો છો?",
    whatDish: (cuisine: string) => `તમે કઈ ${cuisine} વાનગીની રેસીપી ઈચ્છો છો? તમે મને બીજો કોઈ પ્રશ્ન પણ પૂછી શકો છો!`,
    saveRecipe: "રેસીપી સાચવો",
    viewSources: "સ્ત્રોતો જુઓ",
    sources: "સ્ત્રોતો",
    recipeSaved: (recipeName: string) => `સરસ પસંદગી! મેં ${recipeName} ની રેસીપી તમારી કુકબુકમાં સાચવી દીધી છે. તમે ગમે ત્યારે "મારી સાચવેલી રેસિપી બતાવો" ટાઈપ કરીને જોઈ શકો છો. રસોઈનો આનંદ માણો! 📖`,
    showMyRecipes: "મારી સાચવેલી રેસિપી બતાવો",
    sourcesLink: "તમારા માટે અહીં કેટલાક સ્ત્રોતો છે:",
    sourcesNotFound: "આ રેસીપી માટે કોઈ માન્ય સ્ત્રોતો મળ્યા નથી.",
    recipeError: "અરે નહિ! મારા રસોડામાં થોડી ગરબડ થઈ ગઈ. મને તે વાનગી મળી નહીં.",
    textPlaceholder: "એક રેસીપી અથવા પ્રશ્ન પૂછો...",
    recipePlaceholder: "આ રેસીપી વિશે પૂછો અથવા બીજી શોધો...",
    remove: "દૂર કરો",
    recipeRemoved: (recipeName: string) => `${recipeName} તમારી સાચવેલી વાનગીઓમાંથી દૂર કરવામાં આવી છે.`,
    suggestions: "તેના બદલે આમાંથી એક વિશે શું?",
    noExactMatches: "આ રેસીપી માટે કોઈ માન્ય સ્ત્રોતો મળ્યા નથી. અહીં કેટલાક સંબંધિત લિંક્સ છે:",
  },
  kn: {
    greeting: "ನಮಸ್ಕಾರ! ನಾನು ಶೆಫ್ ಬೋರ್ಡ್, ನಿಮ್ಮ ಸ್ನೇಹಪರ ಅಡುಗೆಮನೆಯ ಸಂಗಾತಿ. ಇಂದು ಏನಾದರೂ ರುಚಿಕರವಾದದ್ದನ್ನು ಅಡುಗೆ ಮಾಡೋಣ! 🍳✨",
    selectLang: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
    selectCuisine: "ಇಂದು ನೀವು ಯಾವ ಪಾಕಪದ್ಧತಿಯನ್ನು ಪ್ರಯತ್ನಿಸಲು ಬಯಸುತ್ತೀರಿ?",
    whatDish: (cuisine: string) => `ನೀವು ಯಾವ ${cuisine} ಖಾದ್ಯದ ಪಾಕವಿಧಾನವನ್ನು ಬಯಸುತ್ತೀರಿ? ನೀವು ನನ್ನನ್ನು ಬೇರೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಬಹುದು!`,
    saveRecipe: "ಪಾಕವಿಧಾನವನ್ನು ಉಳಿಸಿ",
    viewSources: "ಮೂಲಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    sources: "ಮೂಲಗಳು",
    recipeSaved: (recipeName: string) => `ಉತ್ತಮ ಆಯ್ಕೆ! ನಾನು ${recipeName} ಪಾಕವಿಧಾನವನ್ನು ನಿಮ್ಮ ಕುಕ್‌ಬುಕ್‌ನಲ್ಲಿ ಉಳಿಸಿದ್ದೇನೆ. "ನನ್ನ ಉಳಿಸಿದ ಪಾಕವಿಧಾನಗಳನ್ನು ತೋರಿಸಿ" ಎಂದು ಟೈಪ್ ಮಾಡುವ ಮೂಲಕ ನೀವು ಅದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ವೀಕ್ಷಿಸಬಹುದು. ಸಂತೋಷದ ಅಡುಗೆ! 📖`,
    showMyRecipes: "ನನ್ನ ಉಳಿಸಿದ ಪಾಕವಿಧಾನಗಳನ್ನು ತೋರಿಸಿ",
    sourcesLink: "ನಿಮಗಾಗಿ ಕೆಲವು ಮೂಲಗಳು ಇಲ್ಲಿವೆ:",
    sourcesNotFound: "ಈ ಪಾಕವಿಧಾನಕ್ಕಾಗಿ ಯಾವುದೇ ಮಾನ್ಯ ಮೂಲಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    recipeError: "ಓಹ್ ಇಲ್ಲ! ನನ್ನ ಅಡುಗೆಮನೆಯಲ್ಲಿ ಸ್ವಲ್ಪ ತೊಡಕು ಉಂಟಾಯಿತು. ನನಗೆ ಆ ಖಾದ್ಯ ಸಿಗಲಿಲ್ಲ.",
    textPlaceholder: "ಪಾಕವಿಧಾನ ಅಥವಾ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...",
    recipePlaceholder: "ಈ ಪಾಕವಿಧಾನದ ಬಗ್ಗೆ ಕೇಳಿ ಅಥವಾ ಇನ್ನೊಂದನ್ನು ಹುಡುಕಿ...",
    remove: "ತೆಗೆದುಹಾಕಿ",
    recipeRemoved: (recipeName: string) => `${recipeName} ಅನ್ನು ನಿಮ್ಮ ಉಳಿಸಿದ ಪಾಕವಿಧಾನಗಳಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.`,
    suggestions: "ಬದಲಾಗಿ ಇವುಗಳಲ್ಲಿ ಒಂದನ್ನು ಹೇಗೆ?",
    noExactMatches: "ಈ ಪಾಕವಿಧಾನಕ್ಕಾಗಿ ಯಾವುದೇ ಮಾನ್ಯ ಮೂಲಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಇಲ್ಲಿ ಕೆಲವು ಸಂಬಂಧಿತ ಲಿಂಕ್‌ಗಳಿವೆ:",
  },
  bn: {
    greeting: "নমস্কার! আমি শেফ বোর্ড, আপনার বন্ধুত্বপূর্ণ রান্নাঘরের সঙ্গী। চলুন আজ সুস্বাদু কিছু রান্না করা যাক! 🍳✨",
    selectLang: "অনুগ্রহ করে আপনার পছন্দের ভাষা নির্বাচন করুন:",
    selectCuisine: "আজ আপনি কোন রান্না চেষ্টা করতে চান?",
    whatDish: (cuisine: string) => `আপনি কোন ${cuisine} খাবারের রেসিপি চান? আপনি আমাকে অন্য কোন প্রশ্নও করতে পারেন!`,
    saveRecipe: "রেসিপি সংরক্ষণ করুন",
    viewSources: "উৎস দেখুন",
    sources: "উৎস",
    recipeSaved: (recipeName: string) => `চমৎকার পছন্দ! আমি আপনার কুকবুকে ${recipeName} এর রেসিপিটি সংরক্ষণ করেছি। আপনি যেকোনো সময় "আমার সংরক্ষিত রেসিপিগুলি দেখান" টাইপ করে এটি দেখতে পারেন। রান্না উপভোগ করুন! 📖`,
    showMyRecipes: "আমার সংরক্ষিত রেসিপিগুলি দেখান",
    sourcesLink: "আপনার জন্য এখানে কিছু উৎস রয়েছে:",
    sourcesNotFound: "এই রেসিপির জন্য কোনো বৈধ উৎস খুঁজে পাওয়া যায়নি।",
    recipeError: "ওহ না! আমার রান্নাঘরে একটু সমস্যা হয়েছে। আমি সেই ডিশটি খুঁজে পাইনি।",
    textPlaceholder: "একটি রেসিপি বা প্রশ্ন জিজ্ঞাসা করুন...",
    recipePlaceholder: "এই রেসিপি সম্পর্কে জিজ্ঞাসা করুন বা অন্য একটি খুঁজুন...",
    remove: "অপসারণ করুন",
    recipeRemoved: (recipeName: string) => `${recipeName} আপনার সংরক্ষিত রেসিপি থেকে সরানো হয়েছে।`,
    suggestions: "পরিবর্তে এইগুলির মধ্যে একটি কেমন?",
    noExactMatches: "এই রেসিপির জন্য কোনো বৈধ উৎস খুঁজে পাওয়া যায়নি। এখানে কিছু সম্পর্কিত লিঙ্ক রয়েছে:",
  },
  te: {
    greeting: "నమస్కారం! నేను చెఫ్ బోర్డ్, మీ స్నేహపూర్వక వంటగది సహచరుడిని. ఈ రోజు రుచికరమైనది వండుదాం! 🍳✨",
    selectLang: "దయచేసి మీకు ఇష్టమైన భాషను ఎంచుకోండి:",
    selectCuisine: "ఈ రోజు మీరు ఏ వంటకాన్ని ప్రయత్నించాలనుకుంటున్నారు?",
    whatDish: (cuisine: string) => `మీరు ఏ ${cuisine} వంటకం కోసం రెసిపీని కోరుకుంటున్నారు? మీరు నన్ను ఏ ఇతర ప్రశ్న అయినా అడగవచ్చు!`,
    saveRecipe: "రెసిపీని సేవ్ చేయండి",
    viewSources: "మూలాలను వీక్షించండి",
    sources: "మూలాలు",
    recipeSaved: (recipeName: string) => `గొప్ప ఎంపిక! నేను ${recipeName} రెసిపీని మీ కుక్‌బుక్‌లో సేవ్ చేసాను. మీరు ఎప్పుడైనా "నా సేవ్ చేసిన రెసిపీలను చూపించు" అని టైప్ చేయడం ద్వారా దాన్ని చూడవచ్చు. సంతోషంగా వండండి! 📖`,
    showMyRecipes: "నా సేవ్ చేసిన రెసిపీలను చూపించు",
    sourcesLink: "మీ కోసం ఇక్కడ కొన్ని మూలాలు ఉన్నాయి:",
    sourcesNotFound: "ఈ రెసిపీకి చెల్లుబాటు అయ్యే మూలాలు ఏవీ కనుగొనబడలేదు.",
    recipeError: "అయ్యో! నా వంటగదిలో కొంచెం సమస్య వచ్చింది. నేను ఆ వంటకాన్ని కనుగొనలేకపోయాను.",
    textPlaceholder: "ఒక రెసిపీ లేదా ప్రశ్న అడగండి...",
    recipePlaceholder: "ఈ రెసిపీ గురించి అడగండి లేదా మరొకటి కనుగొనండి...",
    remove: "తొలగించు",
    recipeRemoved: (recipeName: string) => `${recipeName} మీ సేవ్ చేసిన రెసిపీల నుండి తీసివేయబడింది.`,
    suggestions: "దానికి బదులుగా వీటిలో ఒకటి ఎలా ఉంటుంది?",
    noExactMatches: "ఈ రెసిపీకి చెల్లుబాటు అయ్యే మూలాలు ఏవీ కనుగొనబడలేదు. ఇక్కడ కొన్ని సంబంధిత లింక్‌లు ఉన్నాయి:",
  },
  pa: {
    greeting: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਸ਼ੈੱਫ ਬੋਰਡ ਹਾਂ, ਤੁਹਾਡਾ ਦੋਸਤਾਨਾ ਰਸੋਈ ਸਾਥੀ। ਆਓ ਅੱਜ ਕੁਝ ਸੁਆਦੀ ਪਕਾਈਏ! 🍳✨",
    selectLang: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ:",
    selectCuisine: "ਤੁਸੀਂ ਅੱਜ ਕਿਹੜਾ ਪਕਵਾਨ ਅਜ਼ਮਾਉਣਾ ਚਾਹੋਗੇ?",
    whatDish: (cuisine: string) => `ਤੁਸੀਂ ਕਿਸ ${cuisine} ਪਕਵਾਨ ਦੀ ਰੈਸਿਪੀ ਚਾਹੁੰਦੇ ਹੋ? ਤੁਸੀਂ ਮੈਨੂੰ ਕੋਈ ਹੋਰ ਸਵਾਲ ਵੀ ਪੁੱਛ ਸਕਦੇ ਹੋ!`,
    saveRecipe: "ਰੈਸਿਪੀ ਸੇਵ ਕਰੋ",
    viewSources: "ਸਰੋਤ ਵੇਖੋ",
    sources: "ਸਰੋਤ",
    recipeSaved: (recipeName: string) => `ਸ਼ਾਨਦਾਰ ਚੋਣ! ਮੈਂ ${recipeName} ਦੀ ਰੈਸਿਪੀ ਨੂੰ ਤੁਹਾਡੀ ਕੁੱਕਬੁੱਕ ਵਿੱਚ ਸੇਵ ਕਰ ਲਿਆ ਹੈ। ਤੁਸੀਂ ਕਿਸੇ ਵੀ ਸਮੇਂ "ਮੇਰੀਆਂ ਸੇਵ ਕੀਤੀਆਂ ਰੈਸਿਪੀਜ਼ ਦਿਖਾਓ" ਟਾਈਪ ਕਰਕੇ ਇਸਨੂੰ ਦੇਖ ਸਕਦੇ ਹੋ। ਖਾਣਾ ਪਕਾਉਣ ਦਾ ਅਨੰਦ ਲਓ! 📖`,
    showMyRecipes: "ਮੇਰੀਆਂ ਸੇਵ ਕੀਤੀਆਂ ਰੈਸਿਪੀਜ਼ ਦਿਖਾਓ",
    sourcesLink: "ਤੁਹਾਡੇ ਲਈ ਇੱਥੇ ਕੁਝ ਸਰੋਤ ਹਨ:",
    sourcesNotFound: "ਇਸ ਵਿਅੰਜਨ ਲਈ ਕੋਈ ਵੈਧ ਸਰੋਤ ਨਹੀਂ ਮਿਲੇ।",
    recipeError: "ਓ ਨਹੀਂ! ਮੇਰੀ ਰਸੋਈ ਵਿੱਚ ਥੋੜੀ ਗੜਬੜ ਹੋ ਗਈ ਸੀ। ਮੈਨੂੰ ਉਹ ਪਕਵਾਨ ਨਹੀਂ ਮਿਲਿਆ।",
    textPlaceholder: "ਇੱਕ ਵਿਅੰਜਨ ਜਾਂ ਸਵਾਲ ਪੁੱਛੋ...",
    recipePlaceholder: "ਇਸ ਵਿਅੰਜਨ ਬਾਰੇ ਪੁੱਛੋ ਜਾਂ ਕੋਈ ਹੋਰ ਲੱਭੋ...",
    remove: "ਹਟਾਓ",
    recipeRemoved: (recipeName: string) => `${recipeName} ਨੂੰ ਤੁਹਾਡੀਆਂ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਪਕਵਾਨਾਂ ਤੋਂ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।`,
    suggestions: "ਇਸ ਦੀ ਬਜਾਏ ਇਹਨਾਂ ਵਿੱਚੋਂ ਇੱਕ ਬਾਰੇ ਕੀ?",
    noExactMatches: "ਇਸ ਵਿਅੰਜਨ ਲਈ ਕੋਈ ਵੈਧ ਸਰੋਤ ਨਹੀਂ ਮਿਲੇ। ਇੱਥੇ ਕੁਝ ਸਬੰਧਤ ਲਿੰਕ ਹਨ:",
  },
  ml: {
    greeting: "ഹായ്! ഞാൻ ഷെഫ് ബോർഡ്, നിങ്ങളുടെ സൗഹൃദപരമായ അടുക്കള സഹായി. നമുക്ക് ഇന്ന് രുചികരമായ എന്തെങ്കിലും പാചകം ചെയ്യാം! 🍳✨",
    selectLang: "ദയവായി നിങ്ങളുടെ ഇഷ്ട ഭാഷ തിരഞ്ഞെടുക്കുക:",
    selectCuisine: "ഇന്ന് ഏത് വിഭവം പരീക്ഷിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നു?",
    whatDish: (cuisine: string) => `ഏത് ${cuisine} വിഭവത്തിന്റെ പാചകക്കുറിപ്പാണ് നിങ്ങൾക്ക് വേണ്ടത്? നിങ്ങൾക്ക് എന്നോട് മറ്റേതെങ്കിലും ചോദ്യം ചോദിക്കാം!`,
    saveRecipe: "പാചകക്കുറിപ്പ് സംരക്ഷിക്കുക",
    viewSources: "ഉറവിടങ്ങൾ കാണുക",
    sources: "ഉറവിടങ്ങൾ",
    recipeSaved: (recipeName: string) => `മികച്ച തിരഞ്ഞെടുപ്പ്! ഞാൻ ${recipeName} എന്ന പാചകക്കുറിപ്പ് നിങ്ങളുടെ കുക്ക്ബുക്കിൽ സംരക്ഷിച്ചു. "എന്റെ സംരക്ഷിച്ച പാചകക്കുറിപ്പുകൾ കാണിക്കുക" എന്ന് ടൈപ്പ് ചെയ്ത് നിങ്ങൾക്ക് എപ്പോൾ വേണമെങ്കിലും അത് കാണാം. സന്തോഷകരമായ പാചകം! 📖`,
    showMyRecipes: "എന്റെ സംരക്ഷിച്ച പാചകക്കുറിപ്പുകൾ കാണിക്കുക",
    sourcesLink: "നിങ്ങൾക്കായി ചില ഉറവിടങ്ങൾ ഇതാ:",
    sourcesNotFound: "ഈ പാചകക്കുറിപ്പിന് സാധുവായ ഉറവിടങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    recipeError: "ഓ, ഇല്ല! എന്റെ അടുക്കളയിൽ ഒരു ചെറിയ പിശക് സംഭവിച്ചു. എനിക്ക് ആ വിഭവം കണ്ടെത്താനായില്ല.",
    textPlaceholder: "ഒരു പാചകക്കുറിപ്പ് അല്ലെങ്കിൽ ചോദ്യം ചോദിക്കുക...",
    recipePlaceholder: "ഈ പാചകക്കുറിപ്പിനെക്കുറിച്ച് ചോദിക്കുക അല്ലെങ്കിൽ മറ്റൊന്ന് കണ്ടെത്തുക...",
    remove: "നീക്കം ചെയ്യുക",
    recipeRemoved: (recipeName: string) => `${recipeName} നിങ്ങളുടെ സംരക്ഷിച്ച പാചകക്കുറിപ്പുകളിൽ നിന്ന് നീക്കംചെയ്തു.`,
    suggestions: "പകരം ഇവയിലൊന്ന് എങ്ങനെ?",
    noExactMatches: "ഈ പാചകക്കുറിപ്പിന് സാധുവായ ഉറവിടങ്ങളൊന്നും കണ്ടെത്തിയില്ല. പക്ഷെ, ബന്ധപ്പെട്ട ചില ലിങ്കുകൾ ഇതാ:",
  },
  ur: {
    greeting: "ہیلو! میں شیف بورڈ ہوں، آپ کا دوستانہ باورچی خانے کا ساتھی۔ آئیے آج کچھ مزیدار پکائیں! 🍳✨",
    selectLang: "براہ کرم اپنی پسندیدہ زبان منتخب کریں:",
    selectCuisine: "آج آپ کون سا کھانا آزمانا چاہیں گے؟",
    whatDish: (cuisine: string) => `آپ کس ${cuisine} ڈش کی ترکیب چاہتے ہیں؟ آپ مجھ سے کوئی دوسرا سوال بھی پوچھ سکتے ہیں!`,
    saveRecipe: "ترکیب محفوظ کریں",
    viewSources: "ذرائع دیکھیں",
    sources: "ذرائع",
    recipeSaved: (recipeName: string) => `بہترین انتخاب! میں نے ${recipeName} کی ترکیب آپ کی کک بک میں محفوظ کر لی ہے۔ آپ کسی بھی وقت "میری محفوظ کردہ ترکیبیں دکھائیں" ٹائಪ್ کر کے اسے دیکھ सकते ہیں۔ خوشگوار کھانا پکانا! 📖`,
    showMyRecipes: "میری محفوظ کردہ ترکیبیں دکھائیں",
    sourcesLink: "آپ کے لیے کچھ ذرائع ਇਹ ہیں:",
    sourcesNotFound: "اس ترکیب کے لیے کوئی درست ذریعہ نہیں ملا۔",
    recipeError: "اوہ نہیں! میرے باورچی خانے میں تھوڑی سی گڑਬੜ ہوگئی۔ مجھے وہ ڈش نہیں ملی۔",
    textPlaceholder: "ایک ہدایت یا سوال پوچھیں...",
    recipePlaceholder: "اس ترکیب کے بارے میں پوچھیں یا کوئی اور تلاش کریں...",
    remove: "حذف کریں",
    recipeRemoved: (recipeName: string) => `${recipeName} کو آپ کی محفوظ کردہ ترکیبوں سے हटा दिया गया ہے۔`,
    suggestions: "اس کے بجائے ان میں سے ایک کے بارے میں کیا خیال ہے؟",
    noExactMatches: "اس ترکیب کے لیے کوئی درست ذریعہ نہیں ملا۔ یہاں کچھ متعلقہ لنکس ہیں:",
  },
};
